export enum Roles {
  ADMIN = 'ADMIN',
  MARKET_RELATIONSHIP = 'MARKET_RELATIONSHIP',
  VESTIBULAR_SUPPORT = 'VESTIBULAR_SUPPORT',
  CORRECTOR = 'CORRECTOR',
  SECRETARY = 'SECRETARY',
  FINANCE = 'FINANCE'
}
