export enum DocumentEnum {
  ID = 'ID',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  SCHOOL_RECORDS = 'SCHOOL_RECORDS',
  VOTER_REGISTRATION = 'VOTER_REGISTRATION',
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  CONTRACT = 'CONTRACT'
}
